
import { AiFillStar } from 'react-icons/ai';
import img1 from '../assets/istockphoto-1350560575-170667a.webp';
import img2 from '../assets/pexels-photo-1464625.webp';


const data = [
    {
        image: img1,
        title: "Nike Air Monarch IV",
        star: true,
        reviews:"(123 reviews)",
        prevPrice: "$140.00",
        newPrice: "200",
        company: "Nike",
        color: "White",
        category: "sneakers",
    },
    {
        image: img2,
        title: "Nike Air Monarch IV",
        star: true,
        reviews:"(123 reviews)",
        prevPrice: "$140.00",
        newPrice: "200",
        company: "Nike",
        color: "green",
        category: "sneakers",
    },
    {
        image: img1,
        title: "Nike Air Monarch IV",
        star: true,
        reviews:"(123 reviews)",
        prevPrice: "$140.00",
        newPrice: "200",
        company: "Nike",
        color: "White",
        category: "sneakers",
    },
    {
        image: img2,
        title: "Nike Air Monarch IV",
        star: true,
        reviews:"(123 reviews)",
        prevPrice: "$140.00",
        newPrice: "200",
        company: "Nike",
        color: "green",
        category: "sneakers",
    },
    {
        image: img1,
        title: "Nike Air Monarch IV",
        star: true,
        reviews:"(123 reviews)",
        prevPrice: "$140.00",
        newPrice: "200",
        company: "Nike",
        color: "White",
        category: "sneakers",
    },
    {
        image: img2,
        title: "Nike Air Monarch IV",
        star:true,
        reviews:"(123 reviews)",
        prevPrice: "$140.00",
        newPrice: "200",
        company: "Nike",
        color: "green",
        category: "sneakers",
    },
    {
        image: img1,
        title: "Nike Air Monarch IV",
        star: true,
        reviews:"(123 reviews)",
        prevPrice: "$140.00",
        newPrice: "200",
        company: "Nike",
        color: "White",
        category: "sneakers",
    },
    // {
    //     image: img2,
    //     title: "Nike Air Monarch IV",
    //     star: <AiFillStar/>,
    //     reviews:"(123 reviews)",
    //     prevPrice: "$140.00",
    //     newPrice: "200",
    //     company: "Nike",
    //     color: "green",
    //     category: "sneakers",
    // },
]
export default data